server:
  port: 8090
  servlet:
      context-path: /franc/api
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  tomcat:
    uri-encoding: UTF-8


spring:
  output:
    ansi:
      enabled: always

  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: franc-pool

logging:
  config: classpath:log4j2.xml

#mybatis:
  #mapper-locations: classpath:/mapper/**/*.xml
  #config-location: classpath:mybatis-config.xml